[project]
name = "glm-simple-evals"
version = "0.1.0"
description = "Simple evaluation toolkit for GLM models."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "datasets==3.1.0",
    "numpy==1.26.4",
    "openai==1.98.0",
    "pandas==2.3.1",
    "pylatexenc==2.10",
    "scicode @ git+https://github.com/scicode-bench/SciCode.git",
    "sympy==1.13.1",
    "tqdm==4.67.0",
    "zai-sdk==0.0.2",
]

[tool.uv]
package = false
